FROM python:3.11-alpine

RUN apk add gcc python3-dev musl-dev linux-headers

COPY /pyrope/examples.py /pyrope/exercises.py

COPY . .

RUN python3 -m pip install -r requirements.txt

ENTRYPOINT [ "jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "/work" ]

EXPOSE 8888