name: Docker Image CI

on:
# run this workflow only after the tests were successful
#
# this only works when the file is on default branch
# once this file is on main, the 'workflow_run' rule can be commented in and 'push' can be deleted
#
#  workflow_run:
#    workflows: ['Test PyRope']
#    types: [completed]

  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - dockerfile: Dockerfile_py10
          image-tag: pyrope:latest-py3.10
        - dockerfile: Dockerfile_py11
          image-tag: pyrope:latest-py3.11
        - dockerfile: Dockerfile_py12
          image-tag: pyrope:latest-py3.12
          additional-tag: pyrope:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build the PyRope Docker images
      run: docker build . --file ${{ matrix.dockerfile }} --tag ${{ matrix.image-tag }}
    # give the python3.12 image an additional tag 'latest' with no python version specified
    - if: ${{ matrix.additional-tag }}
      run: docker image tag ${{ matrix.image-tag }} ${{ matrix.additional-tag }}
